version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: olh-postgres
    environment:
      POSTGRES_DB: openlinkedhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d openlinkedhub"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
